apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomini-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomini-pod
  template:
    metadata:
      labels:
        app: gomini-pod
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - name: gomini-pod
        image: gcr.io/mchirico/gomini:test
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 124m
            memory: 512Mi
          limits:
            cpu: 700m
            memory: 1152Mi
        ports:
        - containerPort: 3000
          name: gomini-pod
